#### Numpy 
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures

In [1]:
! pip install numpy 


In [2]:
import numpy as np 
## create array using numpy
##create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
# 1D Array 
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape: (2, 5)
Number of dimensions: 2
Size (number of elements): 10
Data type: int32
Item size (in bytes): 4


In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
## Numpy vectorized operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise Addition 
print(f"Addition = {arr1+arr2}")

## Element wise Substraction  
print(f"Substraction  = {arr1-arr2}")

## Element wise Multiplication  
print(f"Multiplication = {arr1*arr2}")

## Element wise Division 
print(f"Division = {arr2/arr1}")

Addition = [11 22 33 44 55]
Substraction  = [ -9 -18 -27 -36 -45]
Multiplication = [ 10  40  90 160 250]
Division = [10. 10. 10. 10. 10.]


In [18]:
### Universal Function 
arr = np.array([1,2,3,4,5,6])

## square root
print(f"square root Element wise : {np.sqrt(arr)}")

## Exponential 
print(f"Exponential Element wise : {np.exp(arr)}")

## Sine 
print(f"Element wise Sine : {np.sin(arr)}")

## Natural log 
print(f"Element wise Natural log : {np.log(arr)}")


square root Element wise : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential Element wise : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Element wise Sine : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Element wise Natural log : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)
print(arr.shape)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [25]:
print(arr[1:,1:3])
print("\n")
print(arr[2:,1:3])

[[ 6  7]
 [10 11]]


[[10 11]]


In [26]:
print(arr[0][0])
print("\n")
print(arr[0:2,2:])

1


[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
## Modify array elements
arr[0,2]=100
print(arr)

[[100   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:,:]=100
print(arr)

[[100   2 100   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
## statistical concepts
# Normalization - to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5,6])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(f"Mean : {mean}")
print(f"standard deviation : {std_dev}")

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Mean : 3.5
standard deviation : 1.707825127659933
Normalized data: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [32]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [33]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [36]:
data[(data>=20) | (data<=20)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])